name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        zig-version: [0.14.0]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Zig Compiler
      uses: mlugg/setup-zig@v1.2.1

    - name: Build
      run: zig build

    - name: Test
      run: zig build test
